"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Analysis.py']
DATA_FILES = ['Assets.py',
 'Budget.py',
 'Debt.py',
 'Expense.py',
 'Income.py',
 'Metrics.py',
 'HtmlOutput.py',
 'Parser.py',
 'Personal.py',
 'Tax.py',
 'utils.py']
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
